byference:
  application:
    name: samples
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/samples?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
      level:
        com.github.byference.samples.mapper: debug